services:
  crab-track:
    image: mmatiasg/crab-track:v0.2.0
    container_name: crab-track
    tty: false
    volumes:
      - type: bind
        source: /home/matias/workspace/datasets/ICMAN-30-Octubre-2022
        target: /dataset/samples
      - type: bind
        source: /home/matias/workspace/crab-track-app/results
        target: /results
      - type: bind
        source: /home/matias/workspace/crab-track-app/config
        target: /config
    environment:
      YOLO_VERBOSE: false
    command: ["python",
              "main.py",
              "--config_path=/config/run_conf.yaml --track --interpolate_existing_tracks --denormalized_existing_tracks"]
