services:
  crab-track:
    build: .
    image: mmatiasg/crab-track-image:0.1.0
    container_name: crab-track
    tty: true
    volumes:
      - type: bind
        source: /home/matias/workspace/datasets/ICMAN-30-Octubre-2022
        target: /dataset/samples
      - type: bind
        source: /home/matias/workspace/crab-track-app/results
        target: /results
    environment:
      - COLUMNS=500
    command: ["python", "-u", "main.py", "--config_path=config/run_conf.yaml"]
