services:
  crab-track:
    build: .
    image: crab-track-image:0.1.0
    container_name: crab-track
    tty: true
    volumes:
      - type: bind
        source: /Users/matiasgonzalez/workspace/datasets/sample_dataset_icman
        target: /dataset/samples
      - type: bind
        source: /Users/matiasgonzalez/workspace/crab-track-app/results
        target: /results
    environment:
      YOLO_VERBOSE: false
    command: ["python", "main.py", "--config_path=config/run_conf.yaml"]
