model:
  path: models/0.2.0/tracking.onnx
  conf_threshold: 0.8
  nms_threshold: 0.5
  device: cpu
input:
  path: /home/datasets/videos
  extension: mp4
output:
  export_videos: false
  path: /home/results
  disable_progress_bar: true