model:
  path: # models weights
  conf_threshold: 0.8 # detection threshold
  nms_threshold: 0.4 # non maximal threshold (iou threshold in ultralisk)
  device: cpu
input:
  path: # videos input
  extension: # videos extension
output:
  save_results: true
  path: results/ # where to save the results this is the stats and the videos