model:
  path: models/0.2.0/tracking.onnx
  conf_threshold: 0.8
  nms_threshold: 0.5
  device: cpu
#  detection, byte_track
  algorithm: detection
  batch_size: 128
  internal_resolution:
    width: 256
    height: 256
input:
  path: /home/datasets/videos
  extension: mp4
  resolution:
    width: 1920
    height: 1080
output:
  path: /home/results
  render_videos: [""] # Videos to render with bbox and path
multiprocess:
  simultaneous_video_processes: 4 # Number of videos to process concurrently (at the same time)
  threads_per_video: 2 # Number of CPUs allocated to process each video