model:
  path: models/0.2.0/tracking.onnx
  conf_threshold: 0.8
  nms_threshold: 0.5
  device: cpu
input:
  path: ~/workspace/crab-track-app/test_data
  extension: avi
output:
  export_videos: false
  path: /test/results
  disable_progress_bar: true
