name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: python:3.10.12-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install S.O libraries
        run: apt update && apt install -y libgl1 libglib2.0-0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create folders for test
        run: mkdir tests/test_results

      - name: Debug current directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files in current directory:"
          ls -R

      - name: Run tests
        run: python -m unittest discover
